config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', as: 'home'

  resources :posts

  resources :conversations, only: [:index, :create, :destroy] do
    resource :messages, only: [:show, :new, :create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :conversations, only: [:index, :create] do
        resources :messages, only: [:show, :new, :create, :destroy]
      end
    end
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :maps, only: :index

  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @posts_new_3 = Post.order(created_at: :desc).limit(3)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='container-fluid'>

  <div class='row'> <!-- carousel -->
    <div class='col-xs-12 col-md-12'>
      <div id='home-page-carousel' class='carousel slide' data-ride='carousel'>
        <ol class="carousel-indicators">
          <li data-target="#home-page-carousel" data-slide-to="0" class="active"></li>
          <li data-target="#home-page-carousel" data-slide-to="1"></li>
          <li data-target="#home-page-carousel" data-slide-to="2"></li>
          <li data-target="#home-page-carousel" data-slide-to="3"></li>
          <li data-target="#home-page-carousel" data-slide-to="4"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag('bmw-e36.jpg', class:'carousel-image') %>
          </div>

          <div class='item'>
            <%= image_tag('wagon-mercedes.jpg', class:'carousel-image') %>
          </div>

          <div class='item'>
            <%= image_tag('audi-r8.jpg', class:'carousel-image') %>
          </div>

          <div class='item'>
            <%= image_tag('ford-gt350.jpg', class:'carousel-image') %>
          </div>
          <div class='item'>
            <%= image_tag('ferrari-scud.jpg', class:'carousel-image') %>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#home-page-carousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#home-page-carousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div> <!-- carousel -->
    </div> <!-- col -->
  </div> <!-- row -->

  <div class='row'> <!-- What's new -->
    <h1 class='wn-header'> What&#39;s New </h1>
      <% @posts_new_3.each do |post| %>
        <div class='col-xs-12 col-md-4 posts-container'>
          <div class='post-header'>
            <h3><%= link_to "#{post.model_year} #{post.make} #{post.model}", post_path(post) %></h3>
            <h5><%= post.address %></h5>
          </div>
          <hr />
          <div>
            <%= link_to image_tag post.image.url(:default), post_path(post) if post.image.present? %>
            <%= image_tag post.imageurl, class: 'post-image-home' if post.image.present? == false %>
          </div>
          <div class='post-header'>
            <p class='post-price'>$<%= post.price %></p>
          </div>
        </div>
      <% end %>
    <h4 class='pull-right show-more'><%= link_to 'Show More..', posts_path %></h4>
  </div> <!-- row -->

  <hr class='hr-before-map'/>

  <div class='row'>
    <div class='col-xs-12 col-md-6'>
      <div>
        <h1 class='maps-home-header'>Map of Local Cars and Parts </h1>
      </div>
      <div style='width: 100%;'>
        <div id="map" style='width: 100%; height: 400px;'></div>
      </div>

      <script type="text/javascript">
        let handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          let markers = handler.addMarkers(<%= raw posts_json(@posts).to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      </script>
    </div> <!-- col -->
    <div class='hidden-xs hiden-sm col-md-6'>
      <h1 class='forum-home-header '>Recent Forum Posts</h1>
    </div>
    <div class='hidden-xs hiden-sm col-md-6 forum-posts-container'>
      <div class='forum-post-inner'>
        <div class='col-xs-12 col-md-12'>
          <div class='first-forum-post'>
            <h4 class='forum-text text-align-center'><a href='#'>Anyone know where I can find an MK2 Supra</a></h4>
            <p class='forum-paragraph'>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
          <hr class='forum-ruler'/>
          <div>
            <h4 class='forum-text text-align-center'><a href='#'> What local cars are for sale around $10000</a></h4>
            <p class='forum-paragraph'>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
          <hr class='forum-ruler'/>
          <div>
            <h4 class='forum-text text-align-center'><a href='#'>The 240sx Yay or Nay?</a></h4>
            <p class='forum-paragraph'>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- row -->

  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <%= render '/layouts/footer.html.erb' %>
    </div>
  </div>

</div> <!-- container -->