config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', as: 'home'

  resources :posts

  resources :conversations, only: [:index, :create, :destroy] do
    resource :messages, only: [:show, :new, :create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :conversations, only: [:index, :create] do
        resources :messages, only: [:show, :new, :create, :destroy]
      end
    end
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :maps, only: :index

  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :conversations, dependent: :destroy

  before_validation :titleize_make
  geocoded_by :address
  after_validation :geocode

  validates :make, presence: {message: 'Must be provided.'}
  validates :model, presence: {message: 'Must be provided.'}
  validates :odometer, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true,
            numericality: { greater_than_or_equal_to: 0 }
  validates :model_year, numericality: { greater_than_or_equal_to: 0 }
  validates :condition, presence: {message: 'Must be provided.'}
  validates :cylinders, numericality: { greater_than_or_equal_to: 3, less_than_or_equal_to: 12 }
  validates :drivetrain, presence: {message: 'Must be provided.'}
  validates :fuel, presence: {message: 'Must be provided.'}
  validates :paint_colour, presence: {message: 'Must be provided.'}
  validates :title_status, presence: {message: 'Must be provided.'}
  validates :transmission_type, presence: {message: 'Must be provided.'}

  mount_uploader :image, ImageUploader

  private

  def self.search(search_term)
    if search_term
      where('make || model || model_year LIKE ?', "%#{search_term.capitalize}%").order('id DESC')
    else
      order('id ASC')
    end
  end

  def titleize_make
    self.make = make.titleize if make.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :set_page, only: [:index]
  # page where all the posts will be shown
  def index
    @posts = Post.search(params[:term]).paginate(:page => params[:page], :per_page => 9)
  end

  # the show page for a singular post
  def show
    @conversation = Conversation.new
  end

  # new post page
  def new
    @post = Post.new
  end

  # create action for posts
  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      flash[:notice] = 'Post Created'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Problem creating post'
      render :new
    end
  end

  # edit post page
  def edit
    authorize! :edit, @post
  end

  # update action for a post
  def update
    authorize! :update, @post
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post Updated 🤗'
    else
      render :edit, alert: 'Problem Updating Post 😡'
    end
  end

  # destroy action for a post
  def destroy
    authorize! :destroy, @post
    @post.destroy
    redirect_to posts_path, notice: 'Post Deleted 🚗 💨'
  end

  private

  def post_params
    params.require(:post).permit([
      :make,
      :model,
      :odometer,
      :price,
      :model_year,
      :condition,
      :cylinders,
      :drivetrain,
      :fuel,
      :paint_colour,
      :title_status,
      :transmission_type,
      :image,
      :term,
      :imageurl
      ])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def set_page
    @page = params[:page] || 0
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def posts_json(posts)
    Gmaps4rails.build_markers(posts) do |post, marker|
      marker.lat        post.latitude
      marker.lng        post.longitude
      marker.infowindow post.model_year.to_s + ' ' + post.make + ' ' + post.model
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class='col-xs-12 col-md-4 col-md-offset-2'>
    <div class='form-group'>
      <%= f.label :make %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :make, class: 'form-control', placeholder: 'Make' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :model %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :model, class: 'form-control', placeholder: 'Model' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :odometer %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-compass" aria-hidden="true"></i>
        </span>
        <%= f.text_field :odometer, class: 'form-control', placeholder: 'Odometer' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :price %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-usd" aria-hidden="true"></i>
        </span>
        <%= f.text_field :price, class: 'form-control', placeholder: 'Price' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :model_year %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </span>
        <%= f.text_field :model_year, class: 'form-control', placeholder: 'Model Year' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :condition %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :condition, class: 'form-control', placeholder: 'Condition' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :address %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-home" aria-hidden="true"></i>
        </span>
        <%= f.text_field :address, class: 'form-control', placeholder: 'Address' %>
      </div>
    </div>

  </div>

  <div class='col-xs-12 col-md-4'>
    <div class='form-group'>
      <%= f.label :cylinders %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :cylinders, class: 'form-control', placeholder: 'Cylinders' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :drivetrain %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-cogs" aria-hidden="true"></i>
        </span>
        <%= f.text_field :drivetrain, class: 'form-control', placeholder: 'Drivetrain' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :fuel %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-fire" aria-hidden="true"></i>
        </span>
        <%= f.text_field :fuel, class: 'form-control', placeholder: 'Fuel Type' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :paint_colour %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :paint_colour, class: 'form-control', placeholder: 'Paint Colour' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :title_status %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-car" aria-hidden="true"></i>
        </span>
        <%= f.text_field :title_status, class: 'form-control', placeholder: 'Title Status' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :transmission_type %>
      <div class='input-group'>
        <span class='input-group-addon'>
          <i class="fa fa-cogs" aria-hidden="true"></i>
        </span>
        <%= f.text_field :transmission_type, class: 'form-control', placeholder: 'Transmission' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>

  </div>

  <div class='col-xs-12 col-md-12'>

    <div>
      <%= f.submit class: 'btn btn-warning new-post-submit' %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div class='container-fluid'>
  <div class='row form-margin-container'>
    <h1 class='new-post-title'> Edit Post </h1>
    <hr style='border-top: 1px solid black;' />

    <div class='col-md-8 col-md-offset-2 form-container'>
      <%= render 'form' %>
    </div>
  </div>

  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <%= render '/layouts/footer.html.erb' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-xs-12 col-md-8 col-md-offset-2 search'>
      <%= form_tag(posts_path, method: :get) do %>
        <%= text_field_tag :term, params[:term], class: 'search-bar', placeholder: 'Search Posts...' %>
        <%= submit_tag 'Search', name: nil, class:'btn btn-warning' %>
      <% end %>
    </div>

    <% @posts.each do |post| %>
      <div class='col-xs-12 col-md-4 posts-container'>
        <div class='post-header'>
          <h3><%= link_to "#{post.model_year} #{post.make} #{post.model}", post_path(post) %></h3>
          <h5><%= post.address %></h5>
        </div>
        <hr style='color:black;'/>
        <div>
          <%= link_to image_tag post.image.url(:default), post_path(post) if post.image.present? %>
          <%= link_to image_tag(post.imageurl, height: 200), post_path(post) if post.image.present? == false %>
        </div>
        <div class='post-header'>
          <p class='post-price'>$<%= post.price %></p>
        </div>
      </div>
    <% end %>

  </div>

  <div class='pagniation-container'>
    <div class='pages'>
      <%= will_paginate @posts %>
    </div>
  </div>

  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <%= render '/layouts/footer.html.erb' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class='container-fluid'>
  <div class='row form-margin-container'>
    <h1 class='new-post-title'> New Post </h1>
    <hr style='border-top: 1px solid black;' />

    <div class='col-md-8 col-md-offset-2 form-container'>
      <%= render 'form' %>
    </div>
  </div>

  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <%= render '/layouts/footer.html.erb' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class='container-fluid'>
  <div class='row post-show-container'>
    <div class='post-header-container'>
      <h1 class='post-title'><%= "#{@post.model_year} #{@post.make} #{@post.model}" %></h1>
      <hr style='width: 50%;'/>
      <h3 class='post-price'><%= "$""#{@post.price}" %></h3>
    </div>

    <div class='col-xs-12 col-md-6 post-image-container'>

        <% if @post.image.present? %>
          <%= image_tag @post.image.url(:default) %>
        <% else %>
          <%= image_tag @post.imageurl, class: 'post-image' %>
        <% end %>
        <div class='editor'>
          <p>
            <% if can? :edit, @post %>
              <%= link_to 'Edit Post', edit_post_path(@post), style: 'color:black;' %>
            <% end %>
            <% if can? :destroy, @post %>
              <%= link_to 'Delete Post',
                post_path(@post),
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this?' },
                style: 'color:black;' %>
            <% end %>
          </p>
          <p>
            Posted By: <strong><%= @post.user.full_name %></strong>
          </p>
        </div>

    </div>
    <div class='col-xs-12 col-md-6 post-map-container'>
      <div style='width: 100%;'>
        <div id="map" class='post-show-map'></div>
      </div>

      <script>
        let handler = Gmaps.build('Google');
        handler.buildMap({ internal: {id: 'map'}}, function(){
          const markers = handler.addMarkers([
            {
              lat: <%= @post.latitude %>,
              lng: <%= @post.longitude %>,
              infowindow: "<%= @post.model_year %> <%= @post.make %> <%= @post.model %>"
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(12);
        });
      </script>
    </div>
  </div>

  <hr class='hr-after-map'/>
  <h1 class='spec-title'> Specifications </h1>

    <div class='row spec-container'>
      <div class='col-xs-4 col-md-4'>
        <ul class='spec-list'>
          <li class='spec'><strong>Price: </strong>$<%= @post.price %></li>
          <li class='spec'><strong>Odometer:</strong> <%= @post.odometer %> KM</li>
          <li class='spec'><strong>Condition:</strong> <%= @post.condition %></li>
        </ul>
      </div>
      <div class='col-xs-4 col-md-4 verticalLine'>
        <ul class='spec-list'>
          <li class='spec'><strong>Cylinders:</strong> <%= @post.cylinders %></li>
          <li class='spec'><strong>Drivetrain:</strong> <%= @post.drivetrain %></li>
          <li class='spec'><strong>Fuel Type:</strong> <%= @post.fuel %></li>
        </ul>
      </div>
      <div class='col-xs-4 col-md-4 verticalLine'>
        <ul class='spec-list'>
          <li class='spec'><strong>Transmission Type:</strong> <%= @post.transmission_type %></li>
          <li class='spec'><strong>Paint Colour:</strong> <%= @post.paint_colour %></li>
          <li class='spec'><strong>Title Status:</strong> <%= @post.title_status %></li>
        </ul>
      </div>
    </div>


  <div class='row'>
    <div class='col-xs-12 col-md-12 text-align-center'>
      <% if @post.user.id != current_user.id %>
        <div>
        <%= link_to 'Message User', conversations_path(post_id: @post.id, sender_id: current_user.id, recipient_id: @post.user.id), method: 'post', class: 'btn btn-warning message-user-button'%>
        </div>
      <% end %>
      <%= render '/layouts/footer.html.erb' %>
    </div>
  </div>
</div>