config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', as: 'home'

  resources :posts

  resources :conversations, only: [:index, :create, :destroy] do
    resource :messages, only: [:show, :new, :create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :conversations, only: [:index, :create] do
        resources :messages, only: [:show, :new, :create, :destroy]
      end
    end
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :maps, only: :index

  mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="unordered-container">
    <ul>
      <li>
        <div class="footer-icon-container">
          <a href="#" target="_blank"><i class="fa fa-facebook footer-icon" aria-hidden="true"></i></a>
        </div>
      </li>
      <li>
        <div class="footer-icon-container">
          <a href="#" target="_blank"><i class="fa fa-twitter footer-icon" aria-hidden="true"></i></a>
        </div>
      </li>
      <li>
        <div class="footer-icon-container">
          <a href="#" target="_blank"><i class="fa fa-instagram footer-icon" aria-hidden="true"></i></a>
        </div>
      </li>
      <li>
        <div class="footer-icon-container">
          <a href="#" target="_blank"><i class="fa fa-reddit-alien footer-icon" aria-hidden="true"></i></a>
        </div>
      </li>
    </ul>
    <div class="footer-text">
      <h6>Copyright &#9400; 2017</h6>
      <h6>All Rights Reserved &middot; Vagabond LTD.</h6>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond Buy and Sell</title>
    
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCoc0Rtby_hdaDPqmUhGk4aaYEqLJ7o27Y"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div id='logo' class="navbar-header">

          <%= link_to image_tag('vagabond_logo2.png', class: 'logo', height: 65), home_path %>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
            <i class="fa fa-bars" aria-hidden="true" id="toggle-menu"></i>
          </button>

        </div>

        <div id='menu' class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="menu-element-left">
              <%= link_to 'New Post', new_post_path %>
            </li>
            <li class="menu-element-left">
              <%= link_to 'Car Listings', posts_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="menu-element-right">
                <div class="user-name">
                  <%= current_user.first_name %>
                </div>
              </li>
            <% end %>
            <% if user_signed_in? %>
            <li class="menu-element-right">
              <!-- <%= link_to conversations_path do %>
                  Messages
              <% end %> -->
              <a href="javascript:void(0)" onclick="openNav()">Messages</a>
            </li>
            <% else %>
              <li class="menu-element-right">
                <%= link_to new_user_path do %>
                  <i class="fa fa-user-plus" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>
            <li class="menu-element-right">
              <% if user_signed_in? %>
                <%= link_to sessions_path, method: :delete do %>
                  <i class="fa fa-sign-out" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to new_session_path do %>
                  <i class="fa fa-sign-in" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>

      </div>
    </nav>

    <div id='slider-conversation' class='slide-conv'>
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

      <h4 class='conversation-title'> Your Conversations </h4>
      <hr style='border-top: 1px solid #818181;' />
      <% @conversations_slider = Conversation.all %>

      <% @conversations_slider.each do |conversation| %>
        <div>
          <% if current_user.blank? %>
            <div></div>
          <% elsif conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
            <% if conversation.sender_id == current_user.id %>
              <% recipient = User.find(conversation.recipient_id) %>
            <% else %>
              <% recipient = User.find(conversation.sender_id) %>
            <% end %>
            <%= link_to recipient.full_name, conversation_messages_path(conversation)%>
          <% end %>
          <hr style='border-top: 1px solid #818181; width: 40%;' />
        </div>
      <% end %>
    </div>

    <div id="flash-message" style='margin-top:76px; margin-bottom:-85px;'>
      <% if flash[:notice] %>
        <div class='alert alert-success'><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class='alert alert-danger'><%= flash[:alert] %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>